// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [];

export const menuCategories: MenuCategory[] = [
  {
    "id": "at-a-glance",
    "label": "At a Glance",
    "items": [
      {
        "name": "Weingut Frosch Riesling Trocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Weingut Frosch Halbtrocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Weingut Loeff Blauer Spätburgunder Trocken",
        "description": "0,2l, 0,1l",
        "price": ""
      }
    ]
  },
  {
    "id": "wei-weine",
    "label": "Weißweine",
    "items": [
      {
        "name": "Weingut Frosch Riesling Trocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Weingut Frosch Riesling Halbtrocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Müller Thurgau Lieblich",
        "description": "0,2l, 0,1l",
        "price": ""
      }
    ]
  },
  {
    "id": "rose",
    "label": "Rosé",
    "items": [
      {
        "name": "Weingut Frosch Halbtrocken",
        "description": "0,2l, 0,1l",
        "price": ""
      }
    ]
  },
  {
    "id": "rotweine",
    "label": "Rotweine",
    "items": [
      {
        "name": "Weingut Loeff Blauer Spätburgunder Trocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Weingut Loeff Portugieser Halbtrocken",
        "description": "0,2l, 0,1l",
        "price": ""
      },
      {
        "name": "Weingut Loeff Dornfelder Lieblich",
        "description": "0,2l, 0,1l",
        "price": ""
      }
    ]
  },
  {
    "id": "weinschorlen",
    "label": "Weinschorlen",
    "items": [
      {
        "name": "Rieslingschorle Sauer",
        "description": "0,4l, 0,2l",
        "price": ""
      },
      {
        "name": "Rieslingschorle Süß",
        "description": "0,4l, 0,2l",
        "price": ""
      },
      {
        "name": "Roséschorle",
        "description": "0,4l, 0,2l",
        "price": ""
      },
      {
        "name": "Rot Sauer",
        "description": "0,4l, 0,2l",
        "price": ""
      },
      {
        "name": "Cola-Rotwein",
        "description": "0,4l, 0,2l",
        "price": ""
      }
    ]
  },
  {
    "id": "sonstiges",
    "label": "Sonstiges",
    "items": [
      {
        "name": "Krümelmonster",
        "description": "Kleines paniertes schweineschnitzel, wahlweise mit pommes frites oder pfannengemüse",
        "price": ""
      },
      {
        "name": "Donald Duck",
        "description": "6 hausgemachte chicken nuggets, wahlweise mit pommes frites oder pfannengemüse",
        "price": ""
      },
      {
        "name": "Topolino",
        "description": "Spaghetti mit tomatensoße",
        "price": ""
      },
      {
        "name": "Calimero",
        "description": "Spaghetti mit ei und schinken",
        "price": ""
      },
      {
        "name": "Pinocchio",
        "description": "2 bällchen eis (vanille, schoko oder erdbeere), smarties und eine waffeltüte",
        "price": ""
      }
    ]
  }
];
