// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "12er Restaurant",
  "shortName": "12er Restaurant",
  "tagline": "German",
  "logoGlyph": "1",
  "cuisine": "German",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "06134 298312",
  "phoneLink": "tel:+496134298312",
  "email": "",
  "address": {
    "street": "Maaraue 31",
    "cityLine": "55246 Wiesbaden",
    "city": "Wiesbaden"
  },
  "mapsUrl": "https://maps.google.com/?cid=2620168114212418207&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=2620168114212418207&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/hacienda.wiesbaden/",
    "facebook": "https://www.facebook.com/p/12er-Restaurant-100063760175297",
    "tiktok": "https://tiktok.com/@12errestaurant.wiesbaden",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": true
    },
    "titleHidden": false
  },
  "closedDays": [
    1,
    2
  ],
  "closedDaysLabel": "Geschlossen: Montag & Dienstag.",
  "hours": [
    {
      "day": "Montag & Dienstag",
      "time": "Geschlossen",
      "closed": true
    },
    {
      "day": "Mittwoch, Donnerstag, Freitag & Samstag",
      "time": "16:00–23:00 Uhr",
      "closed": false
    },
    {
      "day": "Sonntag",
      "time": "12:00–23:00 Uhr",
      "closed": false
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "12er Restaurant | German in Wiesbaden",
    "description": "12er Restaurant in Wiesbaden. german Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "12er Restaurant",
      "German Wiesbaden",
      "12er Restaurant Wiesbaden"
    ],
    "ogTitle": "12er Restaurant",
    "ogDescription": "12er Restaurant in Wiesbaden. german Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "Christina Schröder",
    "vatId": "",
    "responsiblePerson": "Christina Schröder"
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
