// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.6,
  "totalRatings": 290,
  "reviews": [
    {
      "author": "Wolfgang",
      "rating": 5,
      "text": "Direkt am Sportplatz auf der Maaraue erwartete uns eine gut bürgerliche Küche mit einem sehr guten Preis-Leistungsverhältnis.\n\nDer Service war freundlich und flott. Es war leider auch nicht die Hölle los an diesem heißen Freitagabend bei Musik aus den 70ern und 80ern auf Terrasse.\n\nDas von mir gewählte Cordon bleu kam hervorragend \"handmade\" und gut gefüllt daher und auch der 12er Salat meiner Begleitung kam ungewöhnlich, da mit Hähnchenbrust und zarten Rindfleischstreifen (zur Zeit € 15,90) sehr gut rüber.\n\nDas Ganze wurde begleitet durch einen gespritzten Apfewein; bei dem Wetter genau das richtige.\n\nDie Toilette war ebenerdig und auch aus den 70ern, aber sauber.\nWahrscheinlich, aber nicht getestet, gibt es Parkplätze genau am Haus.\n\nAllgemein eine Empfehlung, wenn man auf gut-bürgerliche Küche steht.",
      "time": "vor einem Monat"
    },
    {
      "author": "Robert Mo.",
      "rating": 5,
      "text": "Immer wieder gern. Kommen hier regelmäßig für eine Kleinigkeit und ein frisches Bier vorbei.",
      "time": "vor einem Monat"
    },
    {
      "author": "Fabian Fuellbier",
      "rating": 5,
      "text": "Nach einem Besuch im Freibad Maaraue noch eine Kleinigkeit essen: das Restaurant liegt direkt gegenüber und die Terrasse sah sehr einladend aus.\nAuch ohne Reservierung gab es noch einen Platz für uns (2 Erw., 2 Kinder).\nAuffallend war bereits bei der Begrüßung, wie gastfreundlich und kinderfreundlich die Betreiber sind. Uns wurden Kinderstühle, Kinderbesteck und Malsachen gebracht.\nDas Essen inkl. Sonderwünsche wurde anstandslos aufgenommen und zügig serviert. Wer mit kleinen Kindern unterwegs ist weiß dies zu schätzen, da die Ausdauer der Kleinen nur begrenzt ist.\n\nNun zum Essen: die Größe der Portionen, die Qualität und das gesamte Preis Leistungsverhältnis waren 1a. Leckere, bodenständige Küche mit herzlichem Service.\n\nWir kommen gerne wieder!",
      "time": "vor 2 Jahren"
    },
    {
      "author": "Ei play You gugg",
      "rating": 5,
      "text": "Wir mögen es hier. Gibt auch live Fußball zu sehen. Also auf’m Platz. Nicht im TV.",
      "time": "vor 2 Monaten"
    },
    {
      "author": "Mario Klouda",
      "rating": 5,
      "text": "Einer unserer absoluten Lieblingsspots. Ob mit dem Auto oder dem Rad. Immer super gut und super entspannt. Tolles Team, leckeres Essen!",
      "time": "vor 5 Monaten"
    }
  ]
};
